"""create s3_downloads_log

Revision ID: d0fc10b729e0
Revises: 
Create Date: 2026-01-14 12:17:07.108925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fc10b729e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_downloads_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mbid', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='wazzdat'
    )
    op.create_index(op.f('ix_wazzdat_s3_downloads_log_id'), 's3_downloads_log', ['id'], unique=False, schema='wazzdat')
    op.create_index(op.f('ix_wazzdat_s3_downloads_log_mbid'), 's3_downloads_log', ['mbid'], unique=False, schema='wazzdat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wazzdat_s3_downloads_log_mbid'), table_name='s3_downloads_log', schema='wazzdat')
    op.drop_index(op.f('ix_wazzdat_s3_downloads_log_id'), table_name='s3_downloads_log', schema='wazzdat')
    op.drop_table('s3_downloads_log', schema='wazzdat')
    # ### end Alembic commands ###
